version: '3.9'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql


  solr:
      image: solr:9.5
      ports:
        - "8983:8983"
      volumes:
        - solr_data:/var/solr
        
  redis:
    image: redis:7.4
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "redis123"]

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      REDIS_HOSTS: redis
      REDIS_HOST: redis
      REDIS_PORT: redis:6379
      REDIS_PASSWORD: redis123
    ports:
      - "8081:8081"

volumes:
  db_data:
  solr_data:


